### ISSUE TITLE
Support for nested compound datasets

### ISSUE THREAD

**Issue by nick-iris** [jamesmudd/jhdf#157]
**Describe the bug**
jHDF fails to read nested compound datasets.

**To Reproduce**
Attached is an HDF5 file called master.ph5 with the following [structure](https://github.com/PIC-IRIS/PH5/wiki/PH5-Structure):

        Experiment_g
            Experiment_t
        Maps_g
            Das_g_1001X1077
            Das_g_1001X1040
            Das_g_1001X1021
            … etc.
        Receivers_g
            Das_g_1001X1389
            Das_g_1001X1398
            Das_g_1001X88
            … etc.
        Reports_g
            Report_t
        Responses_g
            NODE_1C_RESP
            Response_t
        Sorts_g
            Array_t_1001
            Sort_t

When reading the data from the /Experiment_g/Experiment_t dataset using the following program, I get this stack trace:

```java
    import io.jhdf.HdfFile;
    import io.jhdf.api.Dataset;
    import java.io.File;


    public class ph5API {
        public static void main(String[] args) {
            String path = "master.ph5";
            File f = new File(path);
            try (HdfFile hdfFile = new HdfFile(f)) {
                Dataset dataset = hdfFile.getDatasetByPath("/Experiment_g/Experiment_t");
                // data will be a Java array with the dimensions of the HDF5 dataset
                Object data = dataset.getData();
            }
        }
    }
```
Stack trace:

```
Exception in thread "main" io.jhdf.exceptions.HdfException: DatasetReader was passed a type it cant fill. Type: io.jhdf.object.datatype.CompoundDataType
	at io.jhdf.dataset.DatasetReader.readDataset(DatasetReader.java:165)
	at io.jhdf.dataset.CompoundDatasetReader.readDataset(CompoundDatasetReader.java:48)
	at io.jhdf.dataset.DatasetBase.getData(DatasetBase.java:133)
	at edu.iris.ph5api.ph5API.main(ph5API.java:28)
```

**System info:**
- `jhdf` version 0.5.4
- Java 1.8
- macOS Catalina

**Additional context:**
Existing branch containing fix at https://github.com/jamesmudd/jhdf/tree/nested-compound

**Related HDF5 file with nested compound datasets:**
[master.ph5.zip](https://github.com/jamesmudd/jhdf/files/4162477/master.ph5.zip)

**Comment by nick-iris** [comment]
@jamesmudd I'm encountering a similar issue when trying to read the following dataset in from that attached hdf5 file (master.ph5).

```java
Dataset ds = hdfFile.getDatasetByPath("/Experiment_g/Sorts_g/Array_t_001");
System.out.println((LinkedHashMap) ds.getData());
```

results in the following stacktrace:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139)
	at io.jhdf.object.datatype.StringData$NullTerminated.setBufferLimit(StringData.java:101)
	at io.jhdf.dataset.DatasetReader.fillFixedLengthStringData(DatasetReader.java:347)
	at io.jhdf.dataset.DatasetReader.readDataset(DatasetReader.java:140)
	at io.jhdf.dataset.CompoundDatasetReader.readDataset(CompoundDatasetReader.java:50)
	at io.jhdf.dataset.DatasetReader.readDataset(DatasetReader.java:168)
	at io.jhdf.dataset.DatasetBase.getData(DatasetBase.java:132)
```

**Comment by jamesmudd** [comment]
OK think that looks like a separate issue to do with null terminated strings. Will need to take a look.

**Comment by nick-iris** [comment]
> OK think that looks like a separate issue to do with null terminated strings. Will need to take a look.

Thanks, I created a separate issue for this at https://github.com/jamesmudd/jhdf/issues/159.

I'll work on getting a dev environment setup for this project so I can try to address other issues as they arise in the future.

**Comment by jamesmudd** [comment]
I have merged a fix for this https://github.com/jamesmudd/jhdf/pull/161 will be in the next release hopefully soon. Just want to look at bitfield datasets.
