### ISSUE TITLE
Support Implicit Indexing

### ISSUE THREAD

**Issue by jamesmudd** [jamesmudd/jhdf#651]
**Describe the bug**

The file provided in #584  [chunked_new_chunk_indices_no_filter_2d](https://github.com/user-attachments/files/15932880/chunked_new_chunk_indices_no_filter_2d.zip) also contains a implicit index dataset `/chunked_implicit`

Attempting to read it results in
```
[main] INFO io.jhdf.dataset.DatasetBase - Getting data for '/chunked_implicit'...
[main] DEBUG io.jhdf.dataset.chunked.ChunkedDatasetV4 - Creating chunk lookup for '/chunked_implicit'

io.jhdf.exceptions.UnsupportedHdfException: Implicit indexing is currently not supported

	at io.jhdf.dataset.chunked.ChunkedDatasetV4$ChunkLookupLazyInitializer.initialize(ChunkedDatasetV4.java:88)
	at io.jhdf.dataset.chunked.ChunkedDatasetV4$ChunkLookupLazyInitializer.initialize(ChunkedDatasetV4.java:69)
	at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:151)
	at io.jhdf.dataset.chunked.ChunkedDatasetV4.getChunkLookup(ChunkedDatasetV4.java:63)
	at io.jhdf.dataset.chunked.ChunkedDatasetBase.isEmpty(ChunkedDatasetBase.java:316)
	at io.jhdf.dataset.DatasetBase.getData(DatasetBase.java:122)
```
Support need to be added

**Comment by jamesmudd** [comment]
Done in https://github.com/jamesmudd/jhdf/pull/655
