### ISSUE TITLE
Error running on Java 8

### ISSUE THREAD

**Issue by jamesmudd** [jamesmudd/jhdf#88]
When running on Java 8 the following error is received
```
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at io.jhdf.Superblock.readSuperblock(Superblock.java:83)
	at io.jhdf.HdfFile.<init>(HdfFile.java:78)
	at com.company.PrintTree.main(PrintTree.java:33)
```
This occurs because the jar was compiled using Java 11.

**Comment by jamesmudd** [comment]
Fixed in v0.4.4. The build was made using Java 1.8
